In [14]:
import pandas as pd

# File CSV
file_glucose = "guladarahpuasa.csv"
file_hba1c = "hba1c.csv"
file_insulin = "insulin.csv"
file_demografi = "demografi.csv"
file_tekanandarah = "tekanandarah.csv"
file_bmi = "bmi.csv"
file_gabungan = "data_gabungan.csv"
file_bersih = "data_bersih.csv"

# Baca dengan delimiter titik koma
df_glucose = pd.read_csv(file_glucose, sep=";")
df_hba1c   = pd.read_csv(file_hba1c, sep=";")
df_insulin = pd.read_csv(file_insulin, sep=";")
df_demografi = pd.read_csv(file_demografi, sep=";")
df_tekanandarah = pd.read_csv(file_tekanandarah, sep=";")
df_bmi = pd.read_csv(file_bmi, sep=";")
df_data_gabungan = pd.read_csv(file_gabungan, sep=";")
df_data_bersih = pd.read_csv(file_bersih, sep=";")

# Tampilkan 5 baris pertama
print("✅ Data Glukosa:")
print(df_glucose.head(), "\n")

print("✅ Data HbA1c:")
print(df_hba1c.head(), "\n")

print("✅ Data Insulin:")
print(df_insulin.head(),"\n")

print("✅ Data demografi:")
print(df_demografi.head(), "\n")

print("✅ Data tekanan darah:")
print(df_tekanandarah.head(), "\n")

print("✅ Data Bmi:")
print(df_bmi.head(),"\n")

print("✅ Data Gabungan:")
print(df_data_gabungan.head(),"\n")

print("✅ Data Bersih:")
print(df_data_bersih.head(),"\n")

✅ Data Glukosa:
       SEQN   fgb
0  130378.0  6.27
1  130379.0  5.50
2  130380.0  8.66
3  130386.0  5.55
4  130394.0  4.88

✅ Data HbA1c:
       SEQN  LBXGH
0  130378.0    5.6
1  130379.0    5.6
2  130380.0    6.2
3  130386.0    5.1
4  130387.0    5.9

✅ Data Insulin:
       SEQN  LBDINSI
0  130378.0    93.18
1  130379.0   119.46
2  130380.0    97.98
3  130386.0    68.28
4  130394.0    43.20

✅ Data demografi:
       SEQN   age
0  130378.0  43.0
1  130379.0  66.0
2  130380.0  44.0
3  130381.0   5.0
4  130382.0   2.0

✅ Data tekanan darah:
       SEQN  systolyc2  Dystolyc 2  Systolyc3  Dyastolic 3
0  130378.0      131.0        96.0      132.0         94.0
1  130379.0      117.0        76.0      113.0         76.0
2  130380.0      112.0        80.0      104.0         76.0
3  130386.0      120.0        74.0      115.0         75.0
4  130387.0      136.0        74.0      145.0         78.0

✅ Data Bmi:
       SEQN  berat  tinggi    BMI
0  130378.0   86.9   179.5  26.97
1  130379.0  101.8   174.2  33.55
2  130380.0   69.4   152.9  29.69
3  130381.0   34.3   120.1  23.78
4  130382.0   13.6     NaN    NaN

✅ Data Gabungan:
       SEQN  berat tinggi    BMI   age   fgb  LBXGH  LBDINSI  systolyc2  \
0  130378.0   86.9  179.5  26.97  43.0  6.27    5.6    93.18      131.0
1  130379.0  101.8  174.2  33.55  66.0  5.50    5.6   119.46      117.0
2  130380.0   69.4  152.9  29.69  44.0  8.66    6.2    97.98      112.0
3  130381.0   34.3  120.1  23.78   5.0   NaN    NaN      NaN        NaN
4  130382.0   13.6    2.0    NaN   NaN   NaN    NaN      NaN        NaN

   Dystolyc2  Systolyc3  Dystolyc3
0       96.0      132.0       94.0
1       76.0      113.0       76.0
2       80.0      104.0       76.0
3        NaN        NaN        NaN
4        NaN        NaN        NaN

✅ Data Bersih:
       SEQN  berat  tinggi    BMI   age   fgb  hba1c  insulin  avg_systolyc  \
0  130378.0   86.9   179.5  26.97  43.0  6.27    5.6    93.18         131.5
1  130379.0  101.8   174.2  33.55  66.0  5.50    5.6   119.46         115.0
2  130380.0   69.4   152.9  29.69  44.0  8.66    6.2    97.98         108.0
3  130386.0   90.6   173.3  30.17  34.0  5.55    5.1    68.28         117.5
4  130387.0  103.5   155.9  42.58  68.0  5.90  136.0    74.00         145.0

   avg_dystolyc
0          95.0
1          76.0
2          78.0
3          74.5
4          78.0

In [10]:
df_bmi['BMI'] = df_bmi['berat'] / ((df_bmi['tinggi'] / 100) ** 2)

# 4. Simpan ke file baru
output_path = "C:/Users/ASUS/Machine Learning project/bmi_hasil.csv"
df_bmi.to_csv(output_path, index=False)

print(f"File dengan BMI berhasil disimpan di {output_path}")

File dengan BMI berhasil disimpan di C:/Users/ASUS/Machine Learning project/bmi_hasil.csv

In [2]:
import pandas as pd

# ===== 1. Fungsi Rename =====
def safe_rename(df, prefix):
    """Tambahkan prefix ke semua kolom kecuali SEQN."""
    return df.rename(columns={col: f"{prefix}_{col}" for col in df.columns if col != "SEQN"})


# ===== 3. Rename Kolom Satu Kali Saja =====
bmi = safe_rename(df_bmi, "BMI")
demografi = safe_rename(df_demografi, "DEMOGRAFI")
glucose = safe_rename(df_glucose, "GDP")
hba1c = safe_rename(df_hba1c, "HBA1C")
insulin = safe_rename(df_insulin, "INSULIN")
tekanandarah = safe_rename(df_tekanandarah, "TD")

# ===== 4. Merge Berdasarkan SEQN =====
merged = (
    df_bmi.merge(df_demografi, on="SEQN", how="outer")
          .merge(df_glucose, on="SEQN", how="outer")
          .merge(df_hba1c, on="SEQN", how="outer")
          .merge(df_insulin, on="SEQN", how="outer")
          .merge(df_tekanandarah, on="SEQN", how="outer")
)

# ===== 5. Urutkan Berdasarkan SEQN =====
merged = merged.sort_values(by="SEQN")

# ===== 6. Simpan Hasil Gabungan =====
output_path = "C:/Users/ASUS/Machine Learning project/data_gabungan_by_seqn.csv"
merged.to_csv(output_path, index=False)

print(f"File gabungan berhasil dibuat: {output_path}")

File gabungan berhasil dibuat: C:/Users/ASUS/Machine Learning project/data_gabungan_by_seqn.csv

In [12]:
df_bersih = df_data_bersih.dropna(how='any', axis=0)
output_path = "C:/Users/ASUS/Machine Learning project/data_cleaning2.csv"
df_bersih.to_csv(output_path, index=False)

print(f"File gabungan berhasil dibuat: {output_path}")

File gabungan berhasil dibuat: C:/Users/ASUS/Machine Learning project/data_cleaning2.csv

In [22]:
df_data_gabungan.dropna(how='any', axis=0)

,SEQN,berat,tinggi,BMI,age,fgb,LBXGH,LBDINSI,systolyc2,Dystolyc,Systolyc3,Dystolyc3
0,130378.0,86.9,98.3,8.993.168.710.396.160,43.0,6.27,5.6,93.18,131.0,96.0,132.0,94.0
1,130379.0,101.8,114.7,7.737.861.325.059.340,66.0,5.50,5.6,119.46,117.0,76.0,113.0,76.0
2,130380.0,69.4,93.5,79.384.597.786.611,44.0,8.66,6.2,97.98,112.0,80.0,104.0,76.0
8,130386.0,90.6,106.1,8.048.175.347.177.490,34.0,5.55,5.1,68.28,120.0,74.0,115.0,75.0
16,130394.0,76.7,92.1,9.042.241.532.771.930,51.0,4.88,4.8,43.20,110.0,68.0,123.0,67.0
...,...,...,...,...,...,...,...,...,...,...,...,...
11921,142299.0,113.8,121.8,7.670.924.096.947.530,33.0,11.30,9.5,136.62,114.0,76.0,114.0,79.0
11922,142300.0,75.2,97.6,7.894.383.230.314.430,46.0,5.27,5.1,62.10,141.0,90.0,142.0,93.0
11925,142303.0,70.8,111.0,5.746.286.827.367.900,69.0,8.88,8.1,102.54,130.0,70.0,122.0,67.0
11927,142305.0,60.4,89.0,7.625.299.835.879.300,76.0,7.33,6.0,149.16,148.0,78.0,144.0,79.0
11931,142309.0,81.9,96.0,8.886.718.750.000.000,40.0,5.33,5.2,37.32,125.0,82.0,128.0,81.0

In [11]:
print(df_data_bersih.isnull().sum())

SEQN               0
berat              0
tinggi          3089
BMI             3367
age             3373
fgb             4236
LBXGH           4323
LBDINSI         4347
avg_systolyc    4455
avg_dystolyc    5460
dtype: int64

In [8]:
# Menghitung rata-rata untuk sistolik dan diastolik
df_data_gabungan['rerata_sistolik'] = df_data_gabungan[['systolyc2', 'Systolyc3']].mean(axis=1)
df_data_gabungan['rerata_diastolik'] = df_data_gabungan[['Dystolyc2', 'Dystolyc3']].mean(axis=1)

# Setelah itu, hapus kolom-kolom asli yang sudah tidak terpakai
df_data_gabungan= df_data_gabungan.drop(columns=['systolyc2', 'Systolyc3', 'Dystolyc2', 'Dystolyc3'])
df_data_gabungan.to_csv('data_bersih.csv', index=False)