In [1]:
import pandas as pd

# File CSV
file_glucose = "Dataset/guladarahpuasa.csv"
file_hba1c = "Dataset/hba1c.csv"
file_insulin = "Dataset/insulin.csv"
file_demografi = "Dataset/demografi.csv"
file_tekanandarah = "Dataset/tekanandarah.csv"
file_bmi = "Dataset/bmi.csv"
file_gabungan = "Dataset/data_gabungan.csv"
file_bersih = "Dataset/data_bersih.csv"
file_label = "Dataset/data_labeled.csv"
file_hdl ="Dataset/hdl.csv"
file_scaled ="Dataset/data_scaled.csv"

# Baca dengan delimiter titik koma
df_glucose = pd.read_csv(file_glucose, sep=";")
df_hba1c   = pd.read_csv(file_hba1c, sep=";")
df_insulin = pd.read_csv(file_insulin, sep=";")
df_demografi = pd.read_csv(file_demografi, sep=";")
df_tekanandarah = pd.read_csv(file_tekanandarah, sep=";")
df_bmi = pd.read_csv(file_bmi, sep=";")
df_data_gabungan = pd.read_csv(file_gabungan, sep=";")
df_data_bersih = pd.read_csv(file_bersih, sep=";")
df_data_label = pd.read_csv(file_label, sep=";")
df_hdl = pd.read_csv(file_hdl, sep=";")   
df_scaled = pd.read_csv(file_scaled, sep=";")

# Tampilkan 5 baris pertama
print("✅ Data Glukosa:")
print(df_glucose.head(), "\n")

print("✅ Data HbA1c:")
print(df_hba1c.head(), "\n")

print("✅ Data Insulin:")
print(df_insulin.head(),"\n")

print("✅ Data demografi:")
print(df_demografi.head(), "\n")

print("✅ Data tekanan darah:")
print(df_tekanandarah.head(), "\n")

print("✅ Data Bmi:")
print(df_bmi.head(),"\n")

print("✅ Data Gabungan:")
print(df_data_gabungan.head(),"\n")

print("✅ Data Bersih:")
print(df_data_bersih.head(),"\n")

print("✅ Data hdl:")
print(df_hdl.head(),"\n")

✅ Data Glukosa:
       SEQN   fgb
0  130378.0  6.27
1  130379.0  5.50
2  130380.0  8.66
3  130386.0  5.55
4  130394.0  4.88

✅ Data HbA1c:
       SEQN  LBXGH
0  130378.0    5.6
1  130379.0    5.6
2  130380.0    6.2
3  130386.0    5.1
4  130387.0    5.9

✅ Data Insulin:
       SEQN  LBDINSI
0  130378.0    93.18
1  130379.0   119.46
2  130380.0    97.98
3  130386.0    68.28
4  130394.0    43.20

✅ Data demografi:
       SEQN   age
0  130378.0  43.0
1  130379.0  66.0
2  130380.0  44.0
3  130381.0   5.0
4  130382.0   2.0

✅ Data tekanan darah:
       SEQN  systolyc2  Dystolyc 2  Systolyc3  Dyastolic 3
0  130378.0      131.0        96.0      132.0         94.0
1  130379.0      117.0        76.0      113.0         76.0
2  130380.0      112.0        80.0      104.0         76.0
3  130386.0      120.0        74.0      115.0         75.0
4  130387.0      136.0        74.0      145.0         78.0

✅ Data Bmi:
       SEQN  berat  tinggi    BMI
0  130378.0   86.9   179.5  26.97
1  130379.0  101.8   174.2  33.55
2  130380.0   69.4   152.9  29.69
3  130381.0   34.3   120.1  23.78
4  130382.0   13.6     NaN    NaN

✅ Data Gabungan:
       SEQN  berat tinggi    BMI   age   fgb  LBXGH  LBDINSI  systolyc2  \
0  130378.0   86.9  179.5  26.97  43.0  6.27    5.6    93.18      131.0
1  130379.0  101.8  174.2  33.55  66.0  5.50    5.6   119.46      117.0
2  130380.0   69.4  152.9  29.69  44.0  8.66    6.2    97.98      112.0
3  130381.0   34.3  120.1  23.78   5.0   NaN    NaN      NaN        NaN
4  130382.0   13.6    2.0    NaN   NaN   NaN    NaN      NaN        NaN

   Dystolyc2  systolyc3  Dystolyc3
0       96.0      132.0       94.0
1       76.0      113.0       76.0
2       80.0      104.0       76.0
3        NaN        NaN        NaN
4        NaN        NaN        NaN

✅ Data Bersih:
       SEQN  berat  tinggi    BMI   age   fgb  hba1c  insulin  avg_systolyc  \
0  130378.0   86.9   179.5  26.97  43.0  6.27    5.6    93.18         131.5
1  130379.0  101.8   174.2  33.55  66.0  5.50    5.6   119.46         115.0
2  130380.0   69.4   152.9  29.69  44.0  8.66    6.2    97.98         108.0
3  130386.0   90.6   173.3  30.17  34.0  5.55    5.1    68.28         117.5
4  130387.0  103.5   155.9  42.58  68.0  5.90  136.0    74.00         145.0

   avg_dystolyc   hdl
0          95.0  1.16
1          76.0  1.55
2          78.0  1.27
3          74.5  1.19
4          78.0  1.09

✅ Data hdl:
       SEQN   hdl
0  130378.0  1.16
1  130379.0  1.55
2  130380.0  1.27
3  130386.0  1.19
4  130387.0  1.09

In [ ]:
df_bmi['BMI'] = df_bmi['berat'] / ((df_bmi['tinggi'] / 100) ** 2)

output_path = "C:/Users/ASUS/Machine Learning project/bmi_hasil.csv"
df_bmi.to_csv(output_path, index=False)

File dengan BMI berhasil disimpan di C:/Users/ASUS/Machine Learning project/bmi_hasil.csv

In [32]:
import pandas as pd

# ===== 1. Fungsi Rename =====
def safe_rename(df, prefix):
    """Tambahkan prefix ke semua kolom kecuali SEQN."""
    return df.rename(columns={col: f"{prefix}_{col}" for col in df.columns if col != "SEQN"})


# ===== 3. Rename Kolom Satu Kali Saja =====
bmi = safe_rename(df_bmi, "BMI")
demografi = safe_rename(df_demografi, "DEMOGRAFI")
glucose = safe_rename(df_glucose, "GDP")
hba1c = safe_rename(df_hba1c, "HBA1C")
insulin = safe_rename(df_insulin, "INSULIN")
tekanandarah = safe_rename(df_tekanandarah, "TD")



# ===== 4. Merge Berdasarkan SEQN =====
merged = (
    df_bmi.merge(df_demografi, on="SEQN", how="outer")
          .merge(df_glucose, on="SEQN", how="outer")
          .merge(df_hba1c, on="SEQN", how="outer")
          .merge(df_insulin, on="SEQN", how="outer")
          .merge(df_tekanandarah, on="SEQN", how="outer")
         
)

# ===== 5. Urutkan Berdasarkan SEQN =====
merged = merged.sort_values(by="SEQN")

# ===== 6. Simpan Hasil Gabungan =====
output_path = "C:/Users/ASUS/Machine Learning project/data_gabungan_by_seqn.csv"
merged.to_csv(output_path, index=False)

print(f"File gabungan berhasil dibuat: {output_path}")

File gabungan berhasil dibuat: C:/Users/ASUS/Machine Learning project/data_gabungan_by_seqn.csv

In [53]:
df_bersih = df_data_bersih.dropna(how='any', axis=0)
output_path = "C:/Users/ASUS/Machine Learning project/data_cleaning2.csv"
df_bersih.to_csv(output_path, index=False)

print(f"File gabungan berhasil dibuat: {output_path}")

File gabungan berhasil dibuat: C:/Users/ASUS/Machine Learning project/data_cleaning2.csv

In [52]:
df_data_bersih.dropna(how='any', axis=0)

,SEQN,berat,tinggi,BMI,age,fgb,LBXGH,LBDINSI,avg_systolyc,avg_dystolyc,hdl
0,130378.0,86.9,179.5,26.97,43.0,6.27,5.6,93.18,131.5,95.0,1.16
1,130379.0,101.8,174.2,33.55,66.0,5.50,5.6,119.46,115.0,76.0,1.55
2,130380.0,69.4,152.9,29.69,44.0,8.66,6.2,97.98,108.0,78.0,1.27
3,130386.0,90.6,173.3,30.17,34.0,5.55,5.1,68.28,117.5,74.5,1.19
4,130387.0,103.5,155.9,42.58,68.0,5.90,136.0,74.00,145.0,78.0,1.09
...,...,...,...,...,...,...,...,...,...,...,...
6468,142303.0,70.8,159.2,27.93,69.0,8.88,8.1,102.54,126.0,68.5,1.40
6469,142305.0,60.4,151.4,26.35,76.0,7.33,6.0,149.16,146.0,78.5,0.93
6470,142307.0,1.0,143.8,0.48,49.0,6.20,132.0,73.00,131.0,72.0,1.63
6471,142309.0,81.9,179.1,25.53,40.0,5.33,5.2,37.32,126.5,81.5,1.71
6472,142310.0,72.1,161.7,27.57,80.0,5.30,121.0,78.00,129.0,81.0,1.14

In [ ]:
print(df_data_bersih.isnull().sum())

SEQN            5725
berat           5725
tinggi          5725
BMI             5725
age             5725
fgb             5725
hba1c           5725
insulin         5725
avg_systolyc    5725
avg_dystolyc    5725
hdl             1370
dtype: int64

In [42]:
# Menghitung rata-rata untuk sistolik dan diastolik
df_data_gabungan['avg_systolyc'] = df_data_gabungan[['systolyc2', 'systolyc3']].mean(axis=1)
df_data_gabungan['avg_dystolyc'] = df_data_gabungan[['Dystolyc2', 'Dystolyc3']].mean(axis=1)

# Setelah itu, hapus kolom-kolom asli yang sudah tidak terpakai
df_data_gabungan = df_data_gabungan.drop(columns=['systolyc2', 'systolyc3', 'Dystolyc2', 'Dystolyc3'])

# Simpan ke dua file CSV
df_data_gabungan.to_csv('data_bersih.csv', index=False)

In [41]:
df_data_gabungan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11933 entries, 0 to 11932
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   SEQN       11933 non-null  float64
 1   berat      11933 non-null  object
 2   tinggi     8844 non-null   object
 3   BMI        8566 non-null   float64
 4   age        8560 non-null   float64
 5   fgb        7697 non-null   float64
 6   LBXGH      7610 non-null   float64
 7   LBDINSI    7586 non-null   float64
 8   systolyc2  7478 non-null   float64
 9   Dystolyc2  6473 non-null   float64
 10  systolyc3  3558 non-null   float64
 11  Dystolyc3  3350 non-null   float64
dtypes: float64(10), object(2)
memory usage: 1.1+ MB

In [2]:
import pandas as pd

try:
    # --- 1. MEMBACA DATASET ---
    data_labeled = pd.read_csv('data_labeled.csv', delimiter=';')
    gender_data = pd.read_csv('gender.csv', delimiter=';')
    print("✅ Berhasil membaca file 'data_labeled.csv' dan 'gender.csv'.")

    # --- 2. MEMPROSES DATA GENDER ---
    gender_data = gender_data.iloc[:, :2]
    gender_data.columns = ['SEQN', 'gender']
    gender_data.dropna(subset=['SEQN', 'gender'], inplace=True)
    
    # --- 3. INISIALISASI GENDER (MEMBUAT KOLOM KATEGORIKAL) ---
    gender_mapping = {1.0: 'Laki-laki', 2.0: 'Perempuan'}
    gender_data['gender'] = gender_data['gender'].map(gender_mapping)
    print("✅ Kolom 'gender' diubah menjadi kategorikal ('Laki-laki' / 'Perempuan').")

    # --- 4. MENGGABUNGKAN DATASET BERDASARKAN SEQN ---
    merged_data = pd.merge(data_labeled, gender_data, on='SEQN', how='left')
    print("✅ Dataset berhasil digabungkan berdasarkan 'SEQN'.")
    
    # Menghapus baris yang mungkin tidak punya data gender setelah digabungkan
    merged_data.dropna(subset=['gender'], inplace=True)

    # --- 5. MENERAPKAN ONE-HOT ENCODING (LANGKAH BARU) ---
    # Ini akan mengubah kolom 'gender' menjadi 'gender_Laki-laki' dan 'gender_Perempuan'
    final_data = pd.get_dummies(merged_data, columns=['gender'], prefix='gender', dtype=float)
    print("✅ One-Hot Encoding berhasil diterapkan pada kolom 'gender'.")

    # --- 6. MENYIMPAN HASIL AKHIR ---
    output_filename = 'data_final_encoded.csv'
    final_data.to_csv(output_filename, index=False, sep=';')
    print(f"✅ Dataset final yang siap untuk model telah disimpan sebagai: '{output_filename}'")

    # --- Tampilkan hasil akhir ---
    print("\nBerikut adalah pratinjau dataset final setelah One-Hot Encoding:")
    # Menampilkan beberapa kolom relevan untuk verifikasi
    print(final_data[['SEQN', 'Status', 'gender_Laki-laki', 'gender_Perempuan']].head())

except FileNotFoundError as e:
    print(f"❌ ERROR: File tidak ditemukan. Pastikan 'data_labeled.csv' dan 'gender.csv' berada di folder yang sama dengan notebook Anda.")
except Exception as e:
    print(f"❌ Terjadi kesalahan: {e}")

✅ Berhasil membaca file 'data_labeled.csv' dan 'gender.csv'.
✅ Kolom 'gender' diubah menjadi kategorikal ('Laki-laki' / 'Perempuan').
✅ Dataset berhasil digabungkan berdasarkan 'SEQN'.
✅ One-Hot Encoding berhasil diterapkan pada kolom 'gender'.
✅ Dataset final yang siap untuk model telah disimpan sebagai: 'data_final_encoded.csv'

Berikut adalah pratinjau dataset final setelah One-Hot Encoding:
       SEQN        Status  gender_Laki-laki  gender_Perempuan
0  130378.0   Prediabetes               1.0               0.0
1  130379.0  Non-diabetes               1.0               0.0
2  130380.0      Diabetes               0.0               1.0
3  130386.0  Non-diabetes               1.0               0.0
4  130387.0      Diabetes               0.0               1.0